# Generated by Django 3.1 on 2020-08-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200819_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ameities',
            new_name='amenities',
        ),
    ]
